### PR TITLE
fix: insulin renamed to insulinSummary crashes StatsResult

### PR DESCRIPTION
**Pull request by k2s**
the crash happens when Carb/Insulin ratio is selected in less common settings of the second status line

### CODE REVIEW

**Comment by Nobukatsuwakui** [comment]
Please forgive me if the question at this place was wrong. I installed app-xdrpcustom-release.apk, but I don't know where to select the insulin or set the insulin name. I want to select tresiba and humalog. I'm Japanese, so I'm not good at English, sorry.

**Comment by k2s** [comment]
> Please forgive me if the question at this place was wrong. I installed app-xdrpcustom-release.apk, but I don't know where to select the insulin or set the insulin name. I want to select tresiba and humalog. I'm Japanese, so I'm not good at English, sorry.

english menu: `MainMenu` / `xDrip+ Predictive Simulation` / `Config Insulin profiles`

**Comment by Nobukatsuwakui** [comment]
What I want is to choose or set two types of insulin, tresiba and humalog.
Please tell me how.

2019年10月17日(木) 1:31 k2s <notifications@github.com>:

**Comment by gruoner** [comment]
@Nobukatsuwakui take the path provided by @k2s. So u will come to profile selector preferences menu. If u can't find it, make sure u have a version containing the "multiple insulin patch".

The preference screen for profile selection is divided in 3 parts
1. enable min. one max. three insulin profiles just by clicking on the checkbox - if you miss a profile (i'm afraid u will miss tresiba) just rise an issue to configure that profile and merge it to the master branch
2. select the basal insulin profile (if u'r on FIT, CT or 2/3 pen schema)
3. select bolus insulin profile (if u'r on FIT, CT or 2/3 pen schema or on pump therapy)

**Comment by k2s** [comment]
@Nobukatsuwakui 

* here are screen shots https://github.com/NightscoutFoundation/xDrip/pull/973
* as I wrote, you need first activate insuline types in `MainMenu` / `xDrip+ Predictive Simulation` / `Config Insulin profiles`
* then you will see buttons with insuline types on entry screen
* there is no Tresiba - you have to ask for it here https://github.com/NightscoutFoundation/xDrip/pull/973 (best with some reference to Tresiba curve)

**Comment by Nobukatsuwakui** [comment]
Please tell me. Even if Lantus is selected with a new xDrip and a value is
entered, it will not be displayed on xDrip. Is this normal behavior? What
would the author want if he selected up to 3 types of insulin?

2019年10月17日(木) 4:21 k2s <notifications@github.com>:

**Comment by gruoner** [comment]
When u select Lantus and save preferences u will get additional buttons in treatment dialog for insulin injections
grafik
U can switch between those and type in the dose u currently injected - when u click the green hook, all defined insulin doses where stored in database and used for prediction.

U can register three types of insulin because we have a therapy with three types of insulin (a fast one, a medium one and a long acting one) called 2/3 pen schema.....

**Comment by Nobukatsuwakui** [comment]
Thank you very much.
“All defined insulin doses are stored in the database and used for
prediction.” This is a record of how much insulin was injected at that time.
Is it not displayed?
The name of Lantus does not appear.

2019年10月19日(土) 7:49 gruoner <notifications@github.com>:

**Comment by Nobukatsuwakui** [comment]
The English text did not seem appropriate. I will ask you questions again.
For example, I selected Lantus and entered a numerical value with the
displayed button, but the Lantus name is not displayed on the HomeScreen.
In other words, it is unclear how many units of insulin were injected at
that time.
Is this behavior the correct result?

2019年10月19日(土) 7:49 gruoner <notifications@github.com>:

**Comment by k2s** [comment]
@Nobukatsuwakui now I understand your question. The [more insulin](https://github.com/NightscoutFoundation/xDrip/pull/973) pull request is work in progress. It is highly demanded functionality between users using pens. @gruoner started to implemnet it and did huge steps forward. Now it got also attention of @jamorham and I believe/hope it will get merged into master in some months.

You are right that after entering the data, *you are not able to distinquish what type of insulin was injected* in the main graph. I ensure you that the information is stored in DB and is stored also in NightScout if sync is configured.

There is no good way how tomaintain tickets related to bigger pull requests. I am adding your [request to my task list](https://github.com/NightscoutFoundation/xDrip/pull/973#issuecomment-541942951) that should be implemented after the basic work is done.

The functionality requires changes in multiple projects (xDrip, NightScout, NightScout Reporter, etc.). You will need to be patient.

**Comment by jamorham** [comment]
I would hope to have a version for review in a few days. There are still some obvious bugs remaining which is why I have't published anything yet. 

The version I'm working on shows which type of insulins were given when you click on the treatment entry and also allows for basal insulin to be excluded from the predictive calculation based on a preference option. 

It also has some backwards compatibility with previous xDrip versions and the entire feature is optional so that users can continue to use a single insulin and the old insulin activity model if they choose.

**Comment by Nobukatsuwakui** [comment]
Thank you very much. Please let me know when it is published. I want to
know on the display on xDrip when and how many units were injected, not the
total of the two types of insulin.

2019年10月19日(土) 19:25 JamOrHam <notifications@github.com>:

**Comment by gruoner** [comment]
i think @jamorham is cuurently working on this requirement via his code review.... but keep in mind: thats all a question of free space in main GUI (even in watch app)

**Comment by Nobukatsuwakui** [comment]
Thank you,I hope so.

2019年10月20日(日) 6:01 gruoner <notifications@github.com>:

**Pull request merged**
